//int pthread_cond_broadcast(pthread_cond_t *);
//int pthread_cond_destroy(pthread_cond_t *);
//int pthread_cond_init(pthread_cond_t *, const pthread_condattr_t *);
//int pthread_cond_signal(pthread_cond_t *);
//int pthread_cond_timedwait(pthread_cond_t *, pthread_mutex_t *, const struct timespec *);
//int pthread_cond_wait(pthread_cond_t *, pthread_mutex_t *);
//int pthread_condattr_destroy(pthread_condattr_t *);
//int pthread_condattr_getclock(const pthread_condattr_t *, clockid_t *);
//int pthread_condattr_getpshared(const pthread_condattr_t *, int *);
//int pthread_condattr_init(pthread_condattr_t *);
//int pthread_condattr_setclock(pthread_condattr_t *, clockid_t);
//int pthread_condattr_setpshared(pthread_condattr_t *, int);
